language: node_js
node_js:
- stable
script:
- npm run verify-test
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: VnKqTbgXD3rVpSEbwltsQGNd/6WiS9TfgZ4ZBAFhzkcKndg2Q6Cfpero+0ca2SR7lfR+tZ5XkE8z0TGQSttO87BkUvD/c0ha4A06GEhE/9JJeERtIXlOF+eThR4/43s8pJorCkaMkNoK1umgPG9H67zf32GmixwhMP8ZE5htrBr306/Ytp8Kkp9FpF+oCdjqRhKWWqfHUZPYknnBuNGvk/OAkBiI8dIUUgViHSTbcGYicG2BRbq5miNpV3wzM6eyovEiRBsmftdHGZf+uzG11VVkm61Qm1kBNxY5xi+Om0n6HycG3p+jSq0S8PrTh8IwJfzzC5IdhkP1CThUX/RLSBVHJszXNYrGTN6QC8+ZDxmlkRYpQXDpKHr4HoIa8bK/nkI9ZzAn6T9xwX1o8dbQTsfbJK3QfEkOuk36vo8e8l2NqBCqcaOeJBt0M7xIcLKOvHIJfSyFtqGx0N0dN9Ie3/8ffrClUwHV80oFUENSI9eokMhWT7fxaf53M9e1vI0rcxqDp7dPtsqNLjzpXFXM2Le7ez43lQLRbtPGujKNfWQY9stjZ0/6HN3VOgToeZZd+xLYDp9DULoZwprmly//Yjb0hTIq1a2BBUUHxO1V4zB8042n3sgfJ08Q43jC7JDGxzrrm7+FLU2755uqilhRgHMuzJdryxKxugrb4dYr6VM=
  app: hacker-news-clone-ssr
  on:
    branch: master
